---
- name: configure Kubernetes Cluster
  hosts: all
  remote_user: root
  tasks:  
  
    - include_vars: group_vars/common.yaml
    
    - name: Update /etc/hosts
      lineinfile:
        line: "{{ ansible_host }}\t{{ inventory_hostname }}"
        path: /etc/hosts

    - name: Disable SELINUX
      shell: |
        sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
        setenforce 0
    
    - name: Disable firewalld
      systemd:
        state: stopped
        enabled: no
        name: firewalld
    
    - name: Enable br-netfilter and overlay modules
      shell: |
        echo "overlay" > /etc/modules-load.d/k8s.conf
        echo "br_netfilter" >> /etc/modules-load.d/k8s.conf
        modprobe overlay
        modprobe br_netfilter
        echo 'net.bridge.bridge-nf-call-iptables = 1' > /etc/sysctl.d/k8s.conf
        echo 'net.bridge.bridge-nf-call-ip6tables = 1' >> /etc/sysctl.d/k8s.conf
        echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.d/k8s.conf
        sysctl --system
        
    - name: Configure Docker Repo - RHEL based
      ansible.builtin.get_url:
        url: "{{ yum_repo }}"
        dest: /etc/yum.repos.d/docker.repo
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Containerd
      yum:
        name: 
          - containerd.io
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Copy  kubernetes.repo
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes packages
        gpgcheck: yes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        enabled: yes 
        exclude:
          - kubelet 
          - kubeadm 
          - kubectl
    
    - name: Install kubeadm packages
      yum:
        name:
          - kubelet 
          - kubeadm 
          - kubectl
        disable_excludes: kubernetes
        
    - name: Enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes

    - name: Remove swap and remove cri from disabled plugins
      shell: |
        sed -i '/swap/d' /etc/fstab
        swapoff -a
        sed -i 's/^disabled_plugins/#disabled_plugins/g' /etc/containerd/config.toml

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Run kubeadm init on Master
      shell: |
        kubeadm config images pull
        kubeadm init --apiserver-advertise-address="{{ ansible_host }}" --pod-network-cidr=192.168.0.0/16
      when: "'master' in group_names"
    
    - name: Set KUBECONFIG variable at root profile
      lineinfile:
        line: export KUBECONFIG=/etc/kubernetes/admin.conf
        path: /root/.bashrc
        state: present
      when: "'master' in group_names"
    
    - name: Create join script
      shell: kubeadm token create --print-join-command > /tmp/k8s_join.sh
      when: "'master' in group_names"
    
    - name: Copy join script
      fetch:
        src: /tmp/k8s_join.sh
        dest: /tmp/k8s_join.sh
        flat: yes
      when: "'master' in group_names"
    
    - name: Install Network pod
      shell: kubectl apply -f "{{ network_plugin_url }}"
      when: "'master' in group_names"

    - name: Copy join script to Workers
      copy:
        src: /tmp/k8s_join.sh
        dest: /tmp
      when: "'workers' in group_names"
    
    - name: Execute join script on Workers
      shell: bash /tmp/k8s_join.sh
      when: "'workers' in group_names"